mulesoft/api-sync-tool

- gulpfile.js
- lib/application.js
- tests/integration/setup.test.js
- Refactor test tasks in Gulp file.
- Added first basic integration test
> Integration tests first approach

- lib/application.js
- lib/commands/cleanupCommand.js
- lib/commands/createCommand.js
- lib/commands/pullCommand.js
- lib/commands/pushCommand.js
- lib/commands/setupCommand.js
- lib/commands/statusCommand.js
- lib/containerFactory.js
- lib/utils/messages.js
- tests/unit/application.test.js
- tests/unit/cleanupCommand.test.js
- tests/unit/createCommand.test.js
- tests/unit/pullCommand.test.js
- tests/unit/pushCommand.test.js
- tests/unit/setupCommand.test.js
- tests/unit/statusCommand.test.js
* Added a --help option to display a command help with full detail
* Changed some tests to resolve the container dependencies inside the test case (we have to change this in all tests)
> DEVTOOLS-49 Added detailed help messages for each command

- lib/services/localService.js
- tests/support/contentGenerator.js
- tests/unit/localService.test.js
- Checks that:
- New files in workspace do not exist in Anypoint Platform.
- Changed files in workspace exist in Anypoint Platform and were not
changed.
- Deleted files in workspace exist in Anypoint Platform.
> DEVTOOLS-76: Calculate conflicts between workspace and API

- lib/controllers/pushController.js
- lib/utils/errors/ConflictsFoundError.js
- lib/utils/errors/index.js
- lib/utils/messages.js
- tests/unit/pushController.test.js
- Cancel push if conflicts are found.
- TODO: implement push -f
> DEVTOOLS-76: Check conflicts before pushing

- lib/api-sync.js
- lib/controllers/pushController.js
- lib/utils/messages.js
- Fixed an error in push controller, when workspace is updated on
errors.
- Avoid unhandled errors appearing in app output.
- Refactor status and conflicts in messages.
> Fix for push command and for errors output

- lib/repositories/fileSystemRepository.js
- tests/unit/fileSystemRepository.test.js
- This avoids showing them in the status and push commands.
> DEVTOOLS-72: Filter meta files in local filesystem

- lib/commands/createCommand.js
- lib/controllers/createController.js
- lib/repositories/apiPlatformRepository.js
- lib/services/apiPlatformService.js
- lib/utils/messages.js
- tests/unit/apiPlatformRepository.test.js
- tests/unit/apiPlatformService.test.js
- tests/unit/createCommand.test.js
- tests/unit/createController.test.js
* Users can now use the create command to add versions to existing API
* Updated the help message for the command
> DEVTOOLS-79 Added create a new version for an API

- lib/utils/messages.js
* Changed all appearances and variations of 'directory' in the UI to matching variations of 'folder'. 
* In the code, directory is still used because it's compliant will all OS and the change to 'folder' is only to be cohesive with API Platform.
* Changed 'API Platform' to 'Anypoint Platform' in all messages
> DEVTOOLS-84 Changed 'directory' to 'folder' in UI

- lib/commands/cleanupCommand.js
- lib/utils/commandRunner.js
- tests/unit/cleanupCommand.test.js
- tests/unit/commandRunner.test.js
> DEVTOOLS-78 CleanupCommand doesn't require authentication

- lib/commands/statusCommand.js
- lib/controllers/pushController.js
- lib/controllers/statusController.js
- lib/services/localService.js
- lib/utils/messages.js
- tests/unit/localService.test.js
- tests/unit/pushController.test.js
- tests/unit/statusController.test.js
- When a locally unchanged file was deleted remotely, the app should
alert the user.
> DEVTOOLS-76: Unchanged local file deleted remotely is a conflict

- lib/application.js
- lib/commands/cleanupCommand.js
- lib/commands/createCommand.js
- lib/commands/pullCommand.js
- lib/commands/pushCommand.js
- lib/commands/setupCommand.js
- lib/commands/statusCommand.js
- lib/containerFactory.js
- lib/controllers/cleanupController.js
- lib/controllers/createController.js
- lib/controllers/pushController.js
- lib/factories/commandFactory.js
- lib/factories/setupStrategyFactory.js
- lib/repositories/apiPlatformRepository.js
- lib/repositories/csRepository.js
- lib/repositories/fileSystemRepository.js
- lib/services/apiPlatformService.js
- lib/services/localService.js
- lib/strategies/validateNoSetupDoneStrategy.js
- lib/strategies/validateSetupDoneStrategy.js
- lib/utils/authenticationRepository.js
- lib/utils/commandRunner.js
- lib/utils/decompresser.js
- lib/utils/workspaceRepository.js
- tests/unit/cleanupCommand.test.js
- tests/unit/decompresser.test.js
* Moved bluebird to a dependency
> DEVTOOLS-88 Added tests for decompresser

- lib/controllers/pushController.js
- tests/unit/pushController.test.js
DEVTOOLS-66: Update workspace after deleting directories
> DEVTOOLS-66: Update workspace after deleting directories

- lib/commands/createCommand.js
- lib/controllers/createController.js
- lib/factories/createStrategyFactory.js
- lib/repositories/apiPlatformRepository.js
- lib/services/localService.js
- lib/utils/commandPrompt.js
- lib/utils/errors/RepeatedAPINameError.js
- lib/utils/errors/RepeatedAPIVersionNameError.js
- lib/utils/errors/index.js
- lib/utils/loginPrompt.js
- lib/utils/messages.js
- tests/unit/commandPrompt.test.js
- tests/unit/createCommand.test.js
- tests/unit/createController.test.js
- tests/unit/createStrategyFactory.test.js
- tests/unit/localService.test.js
* Added errors for create command
* Existing API name
* Existing API version name
* root RAML not found
* orgId not found
* apiId not found
> DEVTOOLS-80 Added an interactive mode for create command

- lib/commands/pushCommand.js
- lib/controllers/pushController.js
- lib/repositories/apiPlatformRepository.js
- lib/strategies/forcePushCleanupStrategy.js
- lib/utils/messages.js
- tests/support/asserts.js
- tests/unit/apiPlatformRepository.test.js
- tests/unit/forcePushCleanupStrategy.test.js
- tests/unit/pushCommand.test.js
- tests/unit/pushController.test.js
* TO DO in this story:
* Other users status command must work after forced push
* Check that the force push won't delete the root raml
> DEVTOOLS-87 Added a force option to push command

- lib/controllers/pushController.js
- tests/support/contentGenerator.js
- tests/unit/pushController.test.js
* changed the code style of the push
> DEVTOOLS-97 Push adds all the information for updated files

- lib/controllers/pullController.js
- lib/controllers/pushController.js
- lib/services/localService.js
- lib/utils/errors/RootRamlDeletedError.js
- lib/utils/errors/index.js
- lib/utils/messages.js
- tests/support/contentGenerator.js
- tests/unit/localService.test.js
- tests/unit/pullController.test.js
- tests/unit/pushController.test.js
* Added the root raml path to the workspace
> DEVTOOLS-69 If the root raml is deleted, push and push -f fail

- lib/utils/messages.js
* Won't change the slashes to the host OS path separator. Windows understand the paths as we are printing them
> DEVTOOLS-30 Removed the first slash that APIPlatform uses in paths

- lib/index.js
- lib/utils/decompresser.js
- lib/utils/workspaceRepository.js
- package.json
- tests/unit/decompresser.test.js
- Add main file for library and configured it in package.json
- Add some methods needed by the library
> Add support to use api-sync as a library (first steps)

- lib/commands/statusCommand.js
- lib/controllers/statusController.js
- lib/index.js
- tests/unit/statusCommand.test.js
- tests/unit/statusController.test.js
- Changed status controller to return status and conflicts in one call
> Add support command in library

- lib/index.js
- Also refactor and comment API Sync library interface
> Add cleanup support to library

- lib/repositories/apiPlatformRepository.js
- tests/unit/apiPlatformRepository.test.js
- It was missing apiId and apiVersionId in the body
> Fix call to addRootRaml

- README.md
I added some use cases and made the introductory text a bit friendlier. 
Next, I will show the commands, their options, and examples, eventually, screenshots.
> Friendlier introductory text
